name: Release

on:
  push:
    branches:
      - main

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v3
            
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: '16'
            registry-url: 'https://registry.npmjs.org'

        - name: Install Dependencies
          run: npm install

        - name: Create Release Pull Request
          uses: changesets/action@v1
          with:
            publish: npm run publish
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
            NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
